CREATE TABLE IF NOT EXISTS "user" (
	email VARCHAR(255) NOT NULL PRIMARY KEY,
	password VARCHAR(63) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
