# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  test:unit:
    desc: Run unit tests
    cmd: gotestsum -- -coverprofile=website.out ./... -test.short

  test:
    desc: Run tests with integration tests
    deps:
      - start:db:test
    cmd: gotestsum -- -coverprofile=website.out -p 1 ./...

  start:db:main:
    status:
      - docker compose ps --format json | jq -e '.Service == "postgres"'
    cmd: docker compose up -d postgres

  start:db:test:
    status:
      - docker compose ps --format json | jq -e '.Service == "postgres-test"'
    cmd: docker compose up -d postgres-test

  start:redis:main:
    status:
      - docker compose ps --format json | jq -e '.Service == "redis"'
    cmd: docker compose up -d redis

  start:dev:
    deps:
      - start:db:main
      - start:redis:main
    desc: Start the server
    env:
      LOG_ENV: development
    dotenv:
      - .env.local
    cmds:
      - air

  start:cms:
    dir: cms/
    cmd: pnpm dev

  dev:
    desc: Start go server, css building, cms and databases with live reload
    cmd: task -p start:dev start:cms build:css:watch

  build:css:
    desc: Build CSS
    method: checksum
    sources:
      - ./views/**/*.go
      - tailwind.css
    generates:
      - static/styles/style.min.css
    cmds:
      - tailwindcss -i ./tailwind.css -o ./static/styles/style.min.css --minify

  build:css:watch:
    desc: Build CSS
    method: checksum
    sources:
      - ./views/**/*.go
      - tailwind.css
    generates:
      - static/styles/style.min.css
    cmds:
      - tailwindcss -i ./tailwind.css -o ./static/styles/style.min.css --minify --watch

  build:docker:
    desc: Build the Docker image
    cmd: docker build -t website .

  migrate:up:
    desc: Run migrations up
    dotenv:
      - .env.local
    cmd: go run cmd/migrate/main.go up

  migrate:down:
    desc: Run migrations down
    dotenv:
      - .env.local
    cmd: go run cmd/migrate/main.go down

  migrate:add:
    desc: Add a new migration. Pass name with `migrate:add -- <name>`
    cmd: migrate create -ext sql -dir storage/migrations -seq {{.CLI_ARGS}}
