/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    installations: Installation;
    exhibitions: Exhibition;
    films: Film;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    installations: InstallationsSelect<false> | InstallationsSelect<true>;
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>;
    films: FilmsSelect<false> | FilmsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'site-settings': SiteSetting;
    about: About;
    cv: Cv;
    dance: Dance;
    contact: Contact;
    'performance-page': PerformancePage;
    'film-page': FilmPage;
    'works-page': WorksPage;
    'pi-playback': PiPlayback;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    cv: CvSelect<false> | CvSelect<true>;
    dance: DanceSelect<false> | DanceSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'performance-page': PerformancePageSelect<false> | PerformancePageSelect<true>;
    'film-page': FilmPageSelect<false> | FilmPageSelect<true>;
    'works-page': WorksPageSelect<false> | WorksPageSelect<true>;
    'pi-playback': PiPlaybackSelect<false> | PiPlaybackSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left empty.
   */
  slug: string;
  category: 'installation' | 'film' | 'performance';
  /**
   * Show on homepage featured grid.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  year: number;
  /**
   * e.g. "Installation / Film / Performance"
   */
  medium?: string | null;
  /**
   * For film/performance, e.g. "12'30\""
   */
  duration?: string | null;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  venue?: string | null;
  /**
   * e.g. "Basel, Switzerland"
   */
  venueLocation?: string | null;
  /**
   * Main image, 16:9 recommended.
   */
  heroImage?: (number | null) | Media;
  /**
   * Card thumbnail, 4:3 recommended.
   */
  thumbnailImage?: (number | null) | Media;
  /**
   * Fallback Vimeo embed URL, used only when no uploaded video is selected.
   */
  vimeoUrl?: string | null;
  /**
   * Optional MP4. When present, this takes precedence over Vimeo.
   */
  video?: (number | null) | Media;
  /**
   * Required poster/fallback image when an uploaded video is selected.
   */
  videoPoster?: (number | null) | Media;
  collaborators?:
    | {
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  performers?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  screenings?:
    | {
        festival: string;
        location: string;
        year: number;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Downloadable resources.
   */
  files?:
    | {
        title: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations".
 */
export interface Installation {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Available for homepage curation.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  year: number;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leading image. At least 2400 px wide is recommended.
   */
  heroImage: number | Media;
  /**
   * Card image. At least 1600 px wide is recommended.
   */
  thumbnailImage?: (number | null) | Media;
  /**
   * Uploaded MP4. Takes precedence over Vimeo.
   */
  video?: (number | null) | Media;
  /**
   * Required poster when an uploaded video is selected.
   */
  videoPoster?: (number | null) | Media;
  /**
   * Vimeo URL used when no uploaded video is selected.
   */
  vimeoUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  materials: string;
  dimensions: string;
  credits?:
    | {
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Available for homepage curation.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  venue: string;
  city: string;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Display label when exact dates are unavailable, e.g. “Spring 2026”.
   */
  dateLabel?: string | null;
  /**
   * Leading image. At least 2400 px wide is recommended.
   */
  heroImage: number | Media;
  /**
   * Card image. At least 1600 px wide is recommended.
   */
  thumbnailImage?: (number | null) | Media;
  /**
   * Uploaded MP4. Takes precedence over Vimeo.
   */
  video?: (number | null) | Media;
  /**
   * Required poster when an uploaded video is selected.
   */
  videoPoster?: (number | null) | Media;
  /**
   * Vimeo URL used when no uploaded video is selected.
   */
  vimeoUrl?: string | null;
  documentation?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  credits?:
    | {
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ordered list of works in this exhibition.
   */
  includedInstallations?: (number | Installation)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films".
 */
export interface Film {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Available for homepage curation.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  year: number;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Leading image. At least 2400 px wide is recommended.
   */
  heroImage: number | Media;
  /**
   * Card image. At least 1600 px wide is recommended.
   */
  thumbnailImage: number | Media;
  /**
   * Uploaded MP4. Takes precedence over Vimeo.
   */
  video?: (number | null) | Media;
  /**
   * Required poster when an uploaded video is selected.
   */
  videoPoster?: (number | null) | Media;
  /**
   * Vimeo URL used when no uploaded video is selected.
   */
  vimeoUrl?: string | null;
  duration?: string | null;
  credits?:
    | {
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  screenings?:
    | {
        festival: string;
        location: string;
        year: number;
        id?: string | null;
      }[]
    | null;
  stills?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'installations';
        value: number | Installation;
      } | null)
    | ({
        relationTo: 'exhibitions';
        value: number | Exhibition;
      } | null)
    | ({
        relationTo: 'films';
        value: number | Film;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featured?: T;
  sortOrder?: T;
  year?: T;
  medium?: T;
  duration?: T;
  subtitle?: T;
  description?: T;
  venue?: T;
  venueLocation?: T;
  heroImage?: T;
  thumbnailImage?: T;
  vimeoUrl?: T;
  video?: T;
  videoPoster?: T;
  collaborators?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  performers?:
    | T
    | {
        name?: T;
        id?: T;
      };
  screenings?:
    | T
    | {
        festival?: T;
        location?: T;
        year?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  files?:
    | T
    | {
        title?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations_select".
 */
export interface InstallationsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  year?: T;
  shortDescription?: T;
  description?: T;
  heroImage?: T;
  thumbnailImage?: T;
  video?: T;
  videoPoster?: T;
  vimeoUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  materials?: T;
  dimensions?: T;
  credits?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  overview?: T;
  venue?: T;
  city?: T;
  startDate?: T;
  endDate?: T;
  dateLabel?: T;
  heroImage?: T;
  thumbnailImage?: T;
  video?: T;
  videoPoster?: T;
  vimeoUrl?: T;
  documentation?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  credits?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  includedInstallations?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films_select".
 */
export interface FilmsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  year?: T;
  description?: T;
  heroImage?: T;
  thumbnailImage?: T;
  video?: T;
  videoPoster?: T;
  vimeoUrl?: T;
  duration?: T;
  credits?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  screenings?:
    | T
    | {
        festival?: T;
        location?: T;
        year?: T;
        id?: T;
      };
  stills?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    /**
     * MP4 video for hero background.
     */
    video?: (number | null) | Media;
    /**
     * Poster/fallback image when video is unavailable.
     */
    fallbackImage?: (number | null) | Media;
    title?: string | null;
    descriptor?: string | null;
  };
  /**
   * Choose up to 3 published projects in homepage order.
   */
  featuredProjects?:
    | (
        | {
            relationTo: 'installations';
            value: number | Installation;
          }
        | {
            relationTo: 'exhibitions';
            value: number | Exhibition;
          }
        | {
            relationTo: 'films';
            value: number | Film;
          }
      )[]
    | null;
  aboutPractice?: {
    /**
     * Blockquote text for homepage about section.
     */
    quote?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  artistName: string;
  /**
   * Short descriptor, e.g. "Canadian artist based in Europe"
   */
  artistDescriptor?: string | null;
  email?: string | null;
  phone?: string | null;
  vimeoUrl?: string | null;
  instagramUrl?: string | null;
  footerBio?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  portrait?: (number | null) | Media;
  headline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  approach?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv".
 */
export interface Cv {
  id: number;
  /**
   * Current full CV as a PDF.
   */
  fullPdf?: (number | null) | Media;
  downloadFilename?: string | null;
  sections?:
    | {
        title: string;
        entries?:
          | {
              year: number;
              /**
               * End year for ranges, e.g. 2025–2026
               */
              yearEnd?: number | null;
              title: string;
              venue?: string | null;
              location?: string | null;
              pieces?:
                | {
                    name: string;
                    role?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sidebarSections?:
    | {
        title: string;
        entries?:
          | {
              year: number;
              /**
               * End year for ranges, e.g. 2025–2026
               */
              yearEnd?: number | null;
              title: string;
              details?: string | null;
              pieces?:
                | {
                    name: string;
                    role?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dance".
 */
export interface Dance {
  id: number;
  heading?: string | null;
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showreel?: {
    /**
     * Uploaded MP4. Takes precedence over Vimeo.
     */
    video?: (number | null) | Media;
    /**
     * Required poster when an uploaded video is selected.
     */
    videoPoster?: (number | null) | Media;
    /**
     * Vimeo URL used when no uploaded video is selected.
     */
    vimeoUrl?: string | null;
  };
  performanceFootage?:
    | {
        title: string;
        year?: number | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Uploaded MP4. Takes precedence over Vimeo.
         */
        video?: (number | null) | Media;
        /**
         * Required poster when an uploaded video is selected.
         */
        videoPoster?: (number | null) | Media;
        /**
         * Vimeo URL used when no uploaded video is selected.
         */
        vimeoUrl?: string | null;
        credits?:
          | {
              name: string;
              role: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  selectedStageWorks?:
    | {
        title: string;
        anchor: string;
        companyOrVenue?: string | null;
        role?: string | null;
        dateOrYear?: string | null;
        image?: (number | null) | Media;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Uploaded MP4. Takes precedence over Vimeo.
         */
        video?: (number | null) | Media;
        /**
         * Required poster when an uploaded video is selected.
         */
        videoPoster?: (number | null) | Media;
        /**
         * Vimeo URL used when no uploaded video is selected.
         */
        vimeoUrl?: string | null;
        credits?:
          | {
              name: string;
              role: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading?: string | null;
  description?: string | null;
  inquiryCategories?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-page".
 */
export interface PerformancePage {
  id: number;
  heading?: string | null;
  description?: string | null;
  backgroundTitle?: string | null;
  /**
   * Dance training and background bio text.
   */
  backgroundContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  affiliations?:
    | {
        organization: string;
        role?: string | null;
        years?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "film-page".
 */
export interface FilmPage {
  id: number;
  heading?: string | null;
  description?: string | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page".
 */
export interface WorksPage {
  id: number;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Choose a different MP4 for each Raspberry Pi display.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pi-playback".
 */
export interface PiPlayback {
  id: number;
  video?: (number | null) | Media;
  /**
   * Upload an MP4 in Media first, then select it for Pi 1.
   */
  pi1Video?: (number | null) | Media;
  /**
   * Upload an MP4 in Media first, then select it for Pi 2.
   */
  pi2Video?: (number | null) | Media;
  /**
   * Upload an MP4 in Media first, then select it for Pi 3.
   */
  pi3Video?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        video?: T;
        fallbackImage?: T;
        title?: T;
        descriptor?: T;
      };
  featuredProjects?: T;
  aboutPractice?:
    | T
    | {
        quote?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  artistName?: T;
  artistDescriptor?: T;
  email?: T;
  phone?: T;
  vimeoUrl?: T;
  instagramUrl?: T;
  footerBio?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  portrait?: T;
  headline?: T;
  bio?: T;
  approach?:
    | T
    | {
        title?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv_select".
 */
export interface CvSelect<T extends boolean = true> {
  fullPdf?: T;
  downloadFilename?: T;
  sections?:
    | T
    | {
        title?: T;
        entries?:
          | T
          | {
              year?: T;
              yearEnd?: T;
              title?: T;
              venue?: T;
              location?: T;
              pieces?:
                | T
                | {
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  sidebarSections?:
    | T
    | {
        title?: T;
        entries?:
          | T
          | {
              year?: T;
              yearEnd?: T;
              title?: T;
              details?: T;
              pieces?:
                | T
                | {
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dance_select".
 */
export interface DanceSelect<T extends boolean = true> {
  heading?: T;
  introduction?: T;
  showreel?:
    | T
    | {
        video?: T;
        videoPoster?: T;
        vimeoUrl?: T;
      };
  performanceFootage?:
    | T
    | {
        title?: T;
        year?: T;
        description?: T;
        video?: T;
        videoPoster?: T;
        vimeoUrl?: T;
        credits?:
          | T
          | {
              name?: T;
              role?: T;
              id?: T;
            };
        id?: T;
      };
  selectedStageWorks?:
    | T
    | {
        title?: T;
        anchor?: T;
        companyOrVenue?: T;
        role?: T;
        dateOrYear?: T;
        image?: T;
        description?: T;
        video?: T;
        videoPoster?: T;
        vimeoUrl?: T;
        credits?:
          | T
          | {
              name?: T;
              role?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  inquiryCategories?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-page_select".
 */
export interface PerformancePageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  backgroundTitle?: T;
  backgroundContent?: T;
  affiliations?:
    | T
    | {
        organization?: T;
        role?: T;
        years?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "film-page_select".
 */
export interface FilmPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page_select".
 */
export interface WorksPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pi-playback_select".
 */
export interface PiPlaybackSelect<T extends boolean = true> {
  video?: T;
  pi1Video?: T;
  pi2Video?: T;
  pi3Video?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}